
OBJ	=	ehdrdataset.obj envidataset.obj gtxdataset.obj ntv2dataset.obj roipacdataset.o

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

